<?php
declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

final class BooksSeed extends AbstractSeed
{
    public function run(): void
    {
        $data = [
            [
                'book_id' => 5,
                'book_title' => 'Normal People',
                'book_description' => 'The author of conversations with friends comes out with another banger',
                'book_author' => 'Sally Rooney',
                'book_price' => '332.00',
                'status' => '',
                'book_genre' => 'Action',
                'book_image' => 'https://cdn.vox-cdn.com/thumbor/p-gGrwlaU4rLikEAgYhupMUhIJc=/0x0:1650x2475/1200x0/filters:focal(0x0:1650x2475):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/13757614/817BsplxI9L.jpg',
                'created_at' => '2024-01-13 08:36:57',
            ],
            [
                'book_id' => 6,
                'book_title' => 'Harry Potter and the deathly harrows',
                'book_description' => 'harry potter faces his greatest enemy so far, will he finally defeat him?',
                'book_author' => 'J.K. Rowling',
                'book_price' => '243.00',
                'status' => '',
                'book_genre' => 'Fiction',
                'book_image' => 'https://hips.hearstapps.com/digitalspyuk.cdnds.net/15/50/1449878132-9781781100264.jpg?resize=980:*',
                'created_at' => '2024-07-04 14:39:18',
            ],
            [
                'book_id' => 7,
                'book_title' => 'The Right Swipe',
                'book_description' => 'a modern day romance story, with modern twists',
                'book_author' => 'Alisha Rai',
                'book_price' => '123.00',
                'status' => '',
                'book_genre' => 'Romance',
                'book_image' => 'https://m.media-amazon.com/images/I/71LwgxyLFKL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-01-13 08:40:52',
            ],
            [
                'book_id' => 8,
                'book_title' => 'To Kill a Mockingbird',
                'book_description' => 'A novel about the serious issues of rape and racial inequality.',
                'book_author' => 'Harper Lee',
                'book_price' => '11.00',
                'status' => '',
                'book_genre' => 'Fiction',
                'book_image' => 'https://m.media-amazon.com/images/I/81gepf1eMqL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 9,
                'book_title' => '1984',
                'book_description' => 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.',
                'book_author' => 'George Orwell',
                'book_price' => '9.00',
                'status' => '',
                'book_genre' => 'Science Fiction',
                'book_image' => 'https://m.media-amazon.com/images/I/61ZewDE3beL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 10,
                'book_title' => 'The Great Gatsby',
                'book_description' => 'A novel about the American dream and the roaring twenties.',
                'book_author' => 'F. Scott Fitzgerald',
                'book_price' => '10.00',
                'status' => '',
                'book_genre' => 'Classic',
                'book_image' => 'https://m.media-amazon.com/images/I/81QuEGw8VPL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 11,
                'book_title' => 'The Catcher in the Rye',
                'book_description' => 'A story about teenage rebellion and angst.',
                'book_author' => 'J.D. Salinger',
                'book_price' => '13.00',
                'status' => '',
                'book_genre' => 'Fiction',
                'book_image' => 'https://m.media-amazon.com/images/I/91fQEUwFMyL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 12,
                'book_title' => 'The Hobbit',
                'book_description' => 'A fantasy novel and children\'s book about the adventures of Bilbo Baggins.',
                'book_author' => 'J.R.R. Tolkien',
                'book_price' => '15.00',
                'status' => '',
                'book_genre' => 'Fantasy',
                'book_image' => 'https://m.media-amazon.com/images/I/71k--OLmZKL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 13,
                'book_title' => 'Pride and Prejudice',
                'book_description' => 'A romantic novel that also critiques the British landed gentry at the end of the 18th century.',
                'book_author' => 'Jane Austen',
                'book_price' => '12.00',
                'status' => '',
                'book_genre' => 'Romance',
                'book_image' => 'https://m.media-amazon.com/images/I/5176rSnUxfL.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 14,
                'book_title' => 'Harry Potter and the Sorcerer\'s Stone',
                'book_description' => 'The first book in the Harry Potter series about a young wizard and his adventures at Hogwarts.',
                'book_author' => 'J.K. Rowling',
                'book_price' => '14.00',
                'status' => '',
                'book_genre' => 'Fantasy',
                'book_image' => 'https://m.media-amazon.com/images/I/91wKDODkgWL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 15,
                'book_title' => 'The Lord of the Rings',
                'book_description' => 'An epic high-fantasy novel about the quest to destroy the One Ring.',
                'book_author' => 'J.R.R. Tolkien',
                'book_price' => '20.00',
                'status' => '',
                'book_genre' => 'Fantasy',
                'book_image' => 'https://m.media-amazon.com/images/I/81nV6x2ey4L._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 16,
                'book_title' => 'Animal Farm',
                'book_description' => 'A satirical allegorical novella that reflects events leading up to the Russian Revolution of 1917.',
                'book_author' => 'George Orwell',
                'book_price' => '8.00',
                'status' => '',
                'book_genre' => 'Political Satire',
                'book_image' => 'https://m.media-amazon.com/images/I/91Lbhwt5RzL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
            [
                'book_id' => 17,
                'book_title' => 'The Chronicles of Narnia',
                'book_description' => 'A series of fantasy novels about the adventures in the magical land of Narnia.',
                'book_author' => 'C.S. Lewis',
                'book_price' => '16.00',
                'status' => '',
                'book_genre' => 'Fantasy',
                'book_image' => 'https://m.media-amazon.com/images/I/81RuC2qCSmL._AC_UF894,1000_QL80_.jpg',
                'created_at' => '2024-06-26 13:04:52',
            ],
        ];

        $posts = $this->table('books');
        $posts->insert($data)->saveData();
    }
}
